version: "3"
services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=jerilcj3@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=johnjose
    depends_on:
      - postgres    

  postgres:
    container_name: postgres
    image: "postgres:15"
    environment:
      - POSTGRES_PASSWORD=johnjose

  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"     # change this port when running in production 

  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=tracker
      - PGPASSWORD=johnjose
      - PGPORT=5432
      
  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: "./client"
    volumes:
      - /app/node_modules
      - ./client:/app
